### PR TITLE
Add TransIP DNS provider

### PR DESCRIPTION
**Pull request by mdbraber**
Add TransIP as DNS provider. Dependent on the merge of https://github.com/xenolf/lego/pull/703

### CODE REVIEW

**Comment by mdbraber** [comment]
xenolf/lego#703 has now been merged, so this can go forward too...

**Comment by mholt** [comment]
Thanks for your contribution!

Coincidentally, changes are happening in the core of Caddy right now that could potentially deprecate DNS provider plugins; they would no longer be needed, and instead, [all of lego's DNS providers](https://github.com/xenolf/lego/tree/master/providers/dns) would be supported by default for every Caddy instance without the need for plugins. (The downside is the Caddy binary will grow in size.) 

There's a poll taking place here: https://caddy.community/t/poll-we-can-end-dns-provider-plugins-should-we/4887?u=matt - I would like to get your opinion!

**Comment by mdbraber** [comment]
Just checking in to see if there's anything holding this merge back?

**Comment by mholt** [comment]
Swamped with thesis work right now, sorry.

**Comment by mholt** [comment]
Is this compatible with the latest changes in lego? There was a big refactoring for lego v2 that we had to update all the plugins for.

**Comment by tbrasser** [comment]
Is this working already? I can't find it in the documentation, but I found this: https://github.com/go-acme/lego/tree/master/providers/dns/transip 

Seems as if everything else is good to go? (pun intended)

**Comment by mdbraber** [comment]
@mholt could you take a look at the new request https://github.com/caddyserver/dnsproviders/pull/56 for this provider?

**Pull request closed without merging**
