### PR TITLE
update rfc2136

### PR DESCRIPTION
**Pull request by lhemala**

### CODE REVIEW

**Review by mholt — CHANGES_REQUESTED** [review]
I think the DNS propagation timeout should be optional, with a default value. What do you think? (In other words: another `case`.)

**Comment by lhemala** [comment]
Yeah that's reasonable

Should it also default to `60s` as in
https://github.com/xenolf/lego/blob/master/providers/dns/rfc2136/rfc2136.go#L33 ?

**Comment by mholt** [comment]
Oh, nice find. It looks like an empty timeout defaults to that: https://github.com/xenolf/lego/blob/5a2fd5039fbba3c06b640be91a2c436bc23f74e8/providers/dns/rfc2136/rfc2136.go#L73 - so we can just pass in an empty string for that case and let the library choose the default.

**Review by mholt — APPROVED** [review]

**Comment by mholt** [comment]
Looks great! Thanks!

**Pull request merged**
