### PR TITLE
Add NIFCLOUD DNS provider

### PR DESCRIPTION
**Pull request by fuku2014**
###  SUMMARY

This PR adds [NIFCLOUD](https://cloud.nifty.com/service/dns.htm) as a provider for the DNS challenge.

Please review and merge it!

(NIFCLOUD is one of the most famous IaaS in Japan)

### CODE REVIEW

**Comment by mholt** [comment]
Thanks for your contribution!

Coincidentally, changes are happening in the core of Caddy right now that could potentially deprecate DNS provider plugins; they would no longer be needed, and instead, [all of lego's DNS providers](https://github.com/xenolf/lego/tree/master/providers/dns) would be supported by default for every Caddy instance without the need for plugins. (The downside is the Caddy binary will grow in size.) 

There's a poll taking place here: https://caddy.community/t/poll-we-can-end-dns-provider-plugins-should-we/4887?u=matt - I would like to get your opinion!

**Comment by fuku2014** [comment]
I see 😇.
I will comment on the forum discussion!

**Comment by mholt** [comment]
Is this compatible with the latest changes in lego (v2.0.1)? Just want to make sure before I merge. Please test if you haven't :)

**Comment by fuku2014** [comment]
I Pushed some updates and test it with lego v2.0.1!

```console
[root@localhost ~]# ./lego --version
lego version 2.0.1 linux/amd64
[root@localhost ~]# ./lego --dns nifcloud --server https://acme-staging-v02.api.letsencrypt.org/directory --email myemail@gmail.com --domains kame-race.com --domains *.kame-race.com run
2019/01/22 10:52:29 [INFO] [kame-race.com, *.kame-race.com] acme: Obtaining bundled SAN certificate
2019/01/22 10:52:29 [INFO] [*.kame-race.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/CwV21THpbZYOHlAe8YippSt63fbBy8nog4EH60BHnrM
2019/01/22 10:52:29 [INFO] [kame-race.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/rgeFZACenonWiB7KNtjTihhEerJDhGbficsnTK34qb8
2019/01/22 10:52:29 [INFO] [*.kame-race.com] acme: use dns-01 solver
2019/01/22 10:52:29 [INFO] [kame-race.com] acme: Could not find solver for: tls-alpn-01
2019/01/22 10:52:29 [INFO] [kame-race.com] acme: Could not find solver for: http-01
2019/01/22 10:52:29 [INFO] [kame-race.com] acme: use dns-01 solver
2019/01/22 10:52:29 [INFO] [*.kame-race.com] acme: Preparing to solve DNS-01
2019/01/22 10:52:32 [INFO] Wait for nifcloud [timeout: 2m0s, interval: 4s]
2019/01/22 10:52:32 [INFO] [kame-race.com] acme: Preparing to solve DNS-01
2019/01/22 10:52:34 [INFO] Wait for nifcloud [timeout: 2m0s, interval: 4s]
2019/01/22 10:52:34 [INFO] [*.kame-race.com] acme: Trying to solve DNS-01
2019/01/22 10:52:34 [INFO] [*.kame-race.com] acme: Checking DNS record propagation using [127.0.0.1:53]
2019/01/22 10:52:34 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/01/22 10:52:40 [INFO] [kame-race.com] The server validated our request
2019/01/22 10:52:40 [INFO] [kame-race.com] acme: Trying to solve DNS-01
2019/01/22 10:52:40 [INFO] [kame-race.com] acme: Checking DNS record propagation using [127.0.0.1:53]
2019/01/22 10:52:40 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2019/01/22 10:52:40 [INFO] [kame-race.com] The server validated our request
2019/01/22 10:52:40 [INFO] [*.kame-race.com] acme: Cleaning DNS-01 challenge
2019/01/22 10:52:43 [INFO] Wait for nifcloud [timeout: 2m0s, interval: 4s]
2019/01/22 10:52:43 [INFO] [kame-race.com] acme: Cleaning DNS-01 challenge
2019/01/22 10:52:45 [INFO] Wait for nifcloud [timeout: 2m0s, interval: 4s]
2019/01/22 10:52:46 [INFO] [kame-race.com, *.kame-race.com] acme: Validations succeeded; requesting certificates
2019/01/22 10:52:47 [INFO] [kame-race.com] Server responded with a certificate.

```

It works fine :tada:

**Comment by mholt** [comment]
Thanks!

**Pull request merged**
